---
- name: Read kdeglobals
  ansible.builtin.shell: cat ~/.config/kdeglobals
  register: kdeglobals

- name: Enable double click
  ansible.builtin.lineinfile:
    path: ~/.config/kdeglobals
    insertafter: '[KDE]'
    line: 'SingleClick=false'
  when: kdeglobals.stdout.find('SingleClick=false') == -1