---
- name: Reade konsolerc
  ansible.builtin.shell: cat ~/.config/konsolerc
  register: konsolerc

- name: Copy konsole profile
  ansible.builtin.copy:
    src: konsole.profile
    dest: ~/.local/share/konsole/konsole.profile
    mode: '0600'

- name: Set konsole default profile
  ansible.builtin.lineinfile:
    path: ~/.config/konsolerc
    insertafter: '[MainWindow]'
    line: 'DefaultProfile=konsole.profile.profile'
  when: kdeglobals.stdout.find('DefaultProfile=konsole.profile.profile') == -1

- name: Set konsole favorite profile
  ansible.builtin.lineinfile:
    path: ~/.config/konsolerc
    insertafter: '[MainWindow]'
    line: 'Favorites=konsole.profile'
  when: kdeglobals.stdout.find('Favorites=konsole.profile') == -1

- name: Set KonsoleWindow section
  ansible.builtin.lineinfile:
    path: ~/.config/konsolerc
    insertafter: '[Desktop Entry]'
    line: '[KonsoleWindow]'
  when: kdeglobals.stdout.find('[KonsoleWindow]') == -1

- name: Hide konsole menu bar by default
  ansible.builtin.lineinfile:
    path: ~/.config/konsolerc
    insertafter: '[KonsoleWindow]'
    line: 'ShowMenuBarByDefault=false'
  when: kdeglobals.stdout.find('ShowMenuBarByDefault=false') == -1

