# Root
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: yes
  roles:
    - zypper
    - user
    - ranger
    - zsh
    - zplug
    - firefox
    # - neovim
    - wireless_driver
    - dnsmasq

# User
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: no
  roles:
    # - flatpak
    # - ranger
    # - zsh
    # - zplug

    # - python
    # - neovim

    - nvchad
    - autostart
    - nerd_fonts
