---
# Root
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: true
  roles:
    - zypper
    - user
    - ranger
    - zsh
    - zplug
    - firefox
    - neovim
    - wireless_driver
    - dnsmasq

# User
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: false
  roles:
    - flatpak
    - ranger
    - zsh
    - zplug
    - python
    - neovim
    - autostart
    - nerd_fonts
