---
# Root
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: yes
  roles:
    - zypper
    - user
    - ranger
    - zsh
    - zplug
    - firefox
    - neovim
    # - nerd_fonts

# User
# - hosts: opensuse
#   remote_user: "{{ ansible_user }}"
#   become: no
#   roles:
#     - flatpak
#     - ranger
#     - zsh
#     - python
#     - neovim
#     # - kde
