# Root
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: true
  roles:
    - zypper
    - user
    - ranger
    - zsh
    - firefox
    - nvchad
    # - wireless_driver
    - dnsmasq

# User
- hosts: opensuse
  remote_user: "{{ ansible_user }}"
  become: false
  roles:
    - flatpak
    - ranger
    - zsh
    - nvchad
    - autostart
    - kde
    # - nerd_fonts
