---
- name: Set zsh as default shell for root
  ansible.builtin.user:
    name: root
    state: present
    shell: /bin/zsh

- name: "Create user {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    append: yes
    shell: /bin/zsh
    groups:
      - docker
      - libvirt
      - libvirtdbus
      - vagrant
      - users

# this works for cockpit

# amresh@chaosrealm  ~  id amresh
# uid=1000(amresh) gid=100(users) groups=454(docker),108(libvirt),457(libvirtdbus),453(vagrant),456(vboxusers),100(users)
# amresh@chaosrealm  ~ 