- name: Set zsh as default shell for root
  ansible.builtin.user:
    name: root
    state: present
    shell: /bin/zsh

- name: "Create user {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    append: true
    shell: /bin/zsh
    groups:
      - libvirt
      - libvirtdbus
      - vagrant
      - users
