- name: Add vs code-insiders repo
  community.general.zypper_repository:
    repo: "https://packages.microsoft.com/yumrepos/vscode"
    autorefresh: true
    enabled: true
    name: vscode
    state: present
    auto_import_keys: true
    disable_gpg_check: true

- name: Perform a dist-upgrade
  community.general.zypper:
    name: "*"
    state: dist-upgrade
    allow_vendor_change: true
    extra_args: "--allow-arch-change"
  notify: reboot

- name: Install zypper packages
  community.general.zypper:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - bat
      - bc
      - broot
      - crun
      - git
      - git-lfs
      - ranger
      - zstd
      - neovim
      - dolphin-plugins
      - ripgrep
      - fzf
      - zsh
      - fd
      - eza
      - eza-zsh-completion
      - fzf-zsh-completion
      - flatpak
      - NetworkManager-vpnc
      - vpnc
      - latte-dock
      - code-insiders
      - filelight
      - kvantum-manager
      - kvantum-qt6
      - cockpit
      - cockpit-bridge
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-podman
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - neofetch
      - virt-manager
      - vagrant
      - vagrant-libvirt
      - sshpass
      - qemu-hw-display-qxl
      - gnome-keyring
      - virt-viewer
      - minikube
      - kubernetes-client
      - helm
      - k9s
      - compsize
      - dnsmasq
      - v4l-utils
      - podman
      - jq
  notify: reboot

- name: Uninstall unnecessary zypper packages
  community.general.zypper:
    name: "{{ packages }}"
    state: absent
    update_cache: true
  vars:
    packages:
      - MozillaFirefox
      - MozillaFirefox-branding-openSUSE
      - patterns-games-games
      - patterns-kde-kde_games
      - kdegames-carddecks-default
      - libkdegames
      - libkdegames-lang
      - libkf5kdegames6
      - skanlite
      - skanlite-lang
      - konversation
      - konversation-lang
      - akregator
      - akregator-lang
      - tigervnc
      - libvlc5
      - libvlccore9
      - vlc
      - vlc-codec-gstreamer
      - vlc-lang
      - vlc-noX
      - vlc-qt
      - vlc-vdpau
      - kate
      - kate-lang
      - kate-plugins
      - libkate1
      - liboggkate1
      - spectacle
      - spectacle-lang
  notify: reboot

- name: Enable services
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: "{{ services }}"
  with_items:
    - cockpit.socket
    - libvirtd.service
  loop_control:
    loop_var: services
