- name: Create ranger config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ranger"
    state: directory
    mode: "0755"

- name: Copy ranger rc.conf
  ansible.builtin.template:
    src: rc.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/ranger/rc.conf"
    mode: "0644"

- name: Clone devicons
  ansible.builtin.git:
    repo: "https://github.com/alexanderjeurissen/ranger_devicons"
    dest:  "{{ ansible_env.HOME }}/.config/ranger/plugins/ranger_devicons"
    depth: 1
    update: yes
