- name: Add the flathub repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ packages }}"
    state: present
    remote: flathub
    method: user
  with_items:
    - com.bitwarden.desktop
    - com.discordapp.Discord
    - com.getpostman.Postman
    - com.microsoft.Teams
    - com.slack.Slack
    - com.stremio.Stremio
    - dev.k8slens.OpenLens
    - org.chromium.Chromium
    - org.ksnip.ksnip
    - org.mozilla.Thunderbird
    - org.onlyoffice.desktopeditors
    - org.qbittorrent.qBittorrent
    - org.remmina.Remmina
    - org.videolan.VLC
    - org.kde.kleopatra
    - sh.cider.Cider
  loop_control:
    loop_var: packages
