---
- name: Add the flathub repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ packages }}"
    state: present
    remote: flathub
    method: user
  with_items:
    - com.bitwarden.desktop
    - com.getpostman.Postman
    - com.microsoft.Teams
    - com.uploadedlobster.peek
    - net.sourceforge.jpdftweak.jPdfTweak
    - org.clementine_player.Clementine
    - org.keepassxc.KeePassXC
    - org.musicbrainz.Picard
    - org.qbittorrent.qBittorrent
    - org.remmina.Remmina
    - org.videolan.VLC
    - org.ksnip.ksnip
    - org.chromium.Chromium
    - com.stremio.Stremio
    - org.wireshark.Wireshark
    - org.onlyoffice.desktopeditors
    - sh.cider.Cider
  loop_control:
    loop_var: packages
