- name: Install starshiprs
  ansible.builtin.shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
  become: true

- name: Correct starship permissions
  ansible.builtin.file:
    path: /usr/local/bin/starship
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy zshenv
  ansible.builtin.template:
    src: zshenv.j2
    dest: "{{ ansible_env.HOME }}/.zshenv"
    mode: "0644"

- name: Copy zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: "0644"

- name: Create starshiprs config dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/starship"
    mode: "0755"
    state: directory

- name: Copy starshiprs config
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/starship/config.toml"
    mode: "0644"
