---
- name: "Create fonts directory for {{ ansible_user }}"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    mode: "0755"
    state: directory

# Sparse checkout of specific fonts since the repo itself is huge
- name: "Install fonts for {{ ansible_user }}"
  ansible.builtin.shell: git clone --depth 1 --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git
  args:
    chdir: "{{ ansible_env.HOME }}/.fonts"

- name: Sparse checkout font
  ansible.builtin.shell: git sparse-checkout set patched-fonts/Hack
  args:
    chdir: "{{ ansible_env.HOME }}/.fonts/nerd-fonts"
