---
- name: Create neovim directories
  ansible.builtin.file:
    path: "{{ dirs }}"
    state: directory
    recurse: yes
    mode: '0750'
  with_items:
    - "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    - "{{ ansible_env.HOME }}/.config/nvim"
  loop_control:
    loop_var: dirs

- name: Download vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: Copy neovim init.vim
  ansible.builtin.copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    mode: '0644'

- name: Install and update plugins
  ansible.builtin.shell: |
    nvim +PlugInstall +qall
    nvim +PlugUpdate +qall

    exit 0
  args:
    executable: /bin/zsh
    warn: no
